version: '3.1'

services:

  reverse-proxy:
       image: "jwilder/nginx-proxy:latest"
       container_name: "reverse-proxy"
       restart: "always"
       ports:
          - "80:80"
          - "443:443"

  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8080:80
    environment: #variables de entorno#
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:   #crea una link entre el host mysql y eso apunta a la ip del contenedor mysql# 
      - mysql:mysql

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/home/viewadmin/wordpress/mysql-data:/var/lib/mysql # mantiene los datos de la base, por más que muera el contenedor#


