version: "3.1"
services:
  proxy:
       image: "jwilder/nginx-proxy:latest"
       container_name: "reverse-proxy"
       restart: "unless-stopped"
       ports:
          - "80:80"
          - "443:443"
       volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
  wordpress:
       image: "wordpress:php7.1-apache"
       ports:
          - 8080:80
       environment: #variables de entorno#
         WORDPRESS_DB_HOST: mysql
         WORDPRESS_DB_USER: root
         WORDPRESS_DB_PASSWORD: ${USER_PASSWROD}
         WORDPRESS_DB_NAME: wordpress
       volumes:
          - wordpress:/var/www/html
  mysql:
       image: "mysql:8.0.13"
       command: --default-authentication-plugin=mysql_native_password
       environment:
         MYSQL_DATABASE: wordpress
         MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
       volumes:
         - mysql:/var/lib/mysql
  phpmyadmin:
       image: phpmyadmin
       restart: "unless-stopped"
       ports:
          - "8000:80"
       environment: 
         PMA_HOST: mysql

volumes:
  mysql:
  wordpress:

